[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cpi_call = "6wkDHL9trHQiFMA4krAZK2gs9wgWZovS9fRGDsMBakUF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[dependencies]
blake3 = "=0.0.0"
regex = "=1.0.0"
cc = "=1.0.0"
